CCMS/Models/SchedulePattern.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CCMS.Models
{
    public class SchedulePattern
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public IList<SchedulePatternRow> Rows { get; set; }
    }
}

CCMS/Controllers/SchedulePatternController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CCMS.Areas.Identity.Data;
using CCMS.Models;
using CCMS.ViewModel;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CCMS.Controllers
{
    [Authorize]
    public class SchedulePatternController : Controller
    {
        private readonly CCMSContext _context;
        private readonly UserManager<CCMSUser> _userManager;
        private readonly SignInManager<CCMSUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public SchedulePatternController(
            CCMSContext context,
            UserManager<CCMSUser> userManager,
            SignInManager<CCMSUser> signInManager,
            RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        [Authorize(Roles = "WFM, Admin")]
        public IActionResult Index()
        {
            IList<SchedulePattern> schedulePatterns = _context.SchedulePatterns.ToList();
            return View(schedulePatterns);
        }

        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Add(SchedulePattern schedulePattern)
        {
            return Redirect("/Index");
        }


    }
}

CCMS/Views/SchedulePattern/Add.cshtml
@model CCMS.Models.SchedulePattern
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Add Schedule Pattern</h1>

<form asp-controller="SchedulePattern" asp-action="Add" method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name"></span>
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description" />
        <span asp-validation-for="Description"></span>
    </div>
    @*<div class="form-group">
    </div>*@
    <div class="form-group">
        <table class="table">
            <tr>
                <th>WeekNumber</th>
                <th>Day of Week</th>
                <th>Time In</th>
                <th>Time Out</th>
            </tr>
            <tbody id="SchedulePatternRows">
                <tr>
                    <td><input class="form-control" asp-for="@Model.Rows[0].WeekNumber" /></td>
                    <td>
                        <table class="table-sm">
                            <tr>
                                <td class="small">M</td>
                                <td class="small">T</td>
                                <td class="small">W</td>
                                <td class="small">R</td>
                                <td class="small">F</td>
                                <td class="small">S</td>
                                <td class="small">U</td>
                            </tr>
                            <tr>
                                <td><input type="checkbox" asp-for="@Model.Rows[0].Mon" /></td>
                                <td><input type="checkbox" asp-for="@Model.Rows[0].Tue" /></td>
                                <td><input type="checkbox" asp-for="@Model.Rows[0].Wed" /></td>
                                <td><input type="checkbox" asp-for="@Model.Rows[0].Thu" /></td>
                                <td><input type="checkbox" asp-for="@Model.Rows[0].Fri" /></td>
                                <td><input type="checkbox" asp-for="@Model.Rows[0].Sat" /></td>
                                <td><input type="checkbox" asp-for="@Model.Rows[0].Sun" /></td>
                            </tr>
                        </table>
                    </td>
                    <td><input class="form-control" type="datetime" asp-for="@Model.Rows[0].TimeIn" /></td>
                    <td><input class="form-control" type="datetime" asp-for="@Model.Rows[0].TimeOut" /></td>
                </tr>
            </tbody>
        </table>
    </div>

    <input type="submit" value="Add Schedule Pattern" />

</form>

CCMS/Views/SchedulePattern/Index.cshtml
@model List<CCMS.Models.SchedulePattern>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>
<p><a asp-controller="SchedulePattern" asp-action="Add">Add SchedulePattern</a></p>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>+</th>
    </tr>
    <tbody id="SchedulePatterns">
        @foreach (var pattern in Model)
        {
            <tr>
                <td></td>
                <td>
                    <button claas="btn btn-primary" type="button" data-toggle="collapse" data-target="#@pattern.Id" aria-expanded="false" aria-controls="@pattern.Id">
                        Expand
                    </button>
                </td>
                <div class="collapse" id="@pattern.Id">
                    <table class="table">
                        <tr>
                            <th>ID</th>
                            <th>WeekNumber</th>
                            <th>DOW</th>
                            <th>Time In</th>
                            <th>Time Out</th>
                        </tr>
                        <tbody id="@pattern.Id">
                            @foreach (var row in pattern.Rows)
                            {
                                <td>@row.Id</td>
                                <td>@row.WeekNumber</td>
                                <td>
                                    <table class="table">
                                        <tr>
                                            <th>M</th>
                                            <th>T</th>
                                            <th>W</th>
                                            <th>R</th>
                                            <th>F</th>
                                            <th>S</th>
                                            <th>U</th>
                                        </tr>
                                        <tbody id="@row.Id">
                                            <tr>
                                                <td type="checkbox" value="@row.Mon"></td>
                                                <td type="checkbox" value="@row.Tue"></td>
                                                <td type="checkbox" value="@row.Wed"></td>
                                                <td type="checkbox" value="@row.Thu"></td>
                                                <td type="checkbox" value="@row.Fri"></td>
                                                <td type="checkbox" value="@row.Sat"></td>
                                                <td type="checkbox" value="@row.Sun"></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                                <td>@row.TimeIn</td>
                                <td>@row.TimeOut</td>
                            }
                        </tbody>
                    </table>
                </div>
            </tr>
        }
    </tbody>
</table>