CCMS/Controllers/EmployeeController.cs
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using CCMS.Models;
using CCMS.ViewModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using CCMS.Areas.Identity.Data;
using CCMS.Utils;

namespace CCMS.Controllers
{

    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly CCMSContext _context;
        private readonly UserManager<CCMSUser> _userManager;
        private readonly SignInManager<CCMSUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        
        public EmployeeController(
            CCMSContext context,
            UserManager<CCMSUser> userManager,
            SignInManager<CCMSUser> signInManager,
            RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        [Authorize(Roles = "WFM, Admin, Human Resources")]
        public IActionResult Index()
        {
            //ViewBag.Title = "Employee";
            IList<Employee> employees = _context.Employees.Include(e => e.ManagementUnit).ToList();
            return View(employees);
        }

        [Authorize(Roles = "WFM, Admin, Human Resources, Staff")]
        public async Task<IActionResult> View(long id)
        {
            Employee employeeUser = _context.Employees.Single(e => e.Id.ToString() == _userManager.GetUserName(User));
            if (User.IsInRole("Staff"))
            {
                if (employeeUser.Id != id)
                {
                    return NotFound();
                }
            }
            //Employee employeeUser = _context.Employees.Single(e => e.Id.ToString() == _userManager.GetUserName(User));
            Employee employee = await _context.Employees.AsNoTracking().SingleAsync(e => e.Id == id);
            ManagementUnit ManagementUnit = await _context.ManagementUnits.AsNoTracking().SingleAsync(d => d.Id == employee.ManagementUnitId);
            IList<TimeOffAllowed> timeOffAlloweds = await _context.TimeOffAlloweds.AsNoTracking().Where(t => t.EmployeeId == id).ToListAsync();
            ViewEmployeeViewModel viewEmployeeViewModel = new ViewEmployeeViewModel
            {
                Employee = employee,
                ManagementUnit = ManagementUnit,
                TimeOffAlloweds = timeOffAlloweds
            };
            return View(viewEmployeeViewModel);
        }

        [Authorize(Roles = "WFM, Admin, Human Resources")]
        public IActionResult Add()
        {
            AddEmployeeViewModel addEmployeeViewModel = new AddEmployeeViewModel(_context.ManagementUnits.ToList());
            return View(addEmployeeViewModel);
        }

        //[Authorize(Roles = "WFM, Admin, Human Resources, Staff")]
        //public async Task<IActionResult> TimeOffRequest()
        //{

        //}

        [Authorize(Roles = "WFM, Admin, Human Resources")]
        [HttpPost]
        public async Task<IActionResult> Add(AddEmployeeViewModel addEmployeeViewModel)
        {
            if(ModelState.IsValid)
            {
                ManagementUnit newEmployeeManagmentUnit = _context.ManagementUnits.Single(d => d.Id == addEmployeeViewModel.ManagementUnitId);
                Employee newEmployee = new Employee
                {
                    FirstName = addEmployeeViewModel.FirstName,
                    MiddleName = addEmployeeViewModel.MiddleName,
                    LastName = addEmployeeViewModel.LastName,
                    HireDate = addEmployeeViewModel.HireDate,
                    ManagementUnit = newEmployeeManagmentUnit
                };

                _context.Employees.Add(newEmployee);
                _context.SaveChanges();

                foreach (int year in Helper.EachYear(newEmployee.HireDate.Year, newEmployee.HireDate.Year + 2))
                {
                    TimeOffAllowed newTimeOffAllowed = new TimeOffAllowed
                    {
                        Employee = newEmployee,
                        Year = year,
                        UTO = 40,
                        PTO = 40
                    };
                    _context.TimeOffAlloweds.Add(newTimeOffAllowed);
                    _context.SaveChanges();
                }

                var newUser = new CCMSUser
                {
                    UserName = newEmployee.Id.ToString(),
                    Employee = newEmployee
                };

                //[DataType(DataType.Password)]
                string pw = "Temp1234!";

                IdentityResult result = await _userManager.CreateAsync(newUser, pw);
                if (result.Succeeded)
                {
                    await _userManager.AddToRoleAsync(newUser, "Staff");
                }

                return Redirect("/Employee");
            }

            return View(addEmployeeViewModel);
        }

        //public IActionResult Update()
    }
}

CCMS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CCMS.Models;
using Microsoft.AspNetCore.Authorization;

namespace CCMS.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult Playground()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CCMS/Controllers/ManagementUnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CCMS.Models;
using CCMS.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CCMS.Controllers
{

    [Authorize(Roles = "WFM, Admin, Human Resources")]
    public class ManagementUnitController : Controller
    {
        private readonly CCMSContext _context;

        public ManagementUnitController(CCMSContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            ViewBag.Title = "ManagmentUnit";
            List<ManagementUnit> ManagmentUnits = _context.ManagementUnits.AsNoTracking().ToList();
            return View(ManagmentUnits);
        }

        [HttpPost]
        public IActionResult Add(AddManagementUnitViewModel addManagmentUnitViewModel)
        {
            if (addManagmentUnitViewModel.Name != null)
            {
                ManagementUnit newManagmentUnit = new ManagementUnit
                {
                    Name = addManagmentUnitViewModel.Name,
                    Description = addManagmentUnitViewModel.Description
                };
                _context.ManagementUnits.Add(newManagmentUnit);
                _context.SaveChanges();
                return Redirect("/ManagmentUnit/View/" + newManagmentUnit.Id);
            }
            else
            {
                return View("Add");
            }
        }

        public async Task<IActionResult> View(long id)
        {
            ManagementUnit ManagmentUnit = await _context.ManagementUnits.AsNoTracking().SingleAsync(d => d.Id == id);
            ViewManagementUnitViewModel viewManagmentUnitViewModel = new ViewManagementUnitViewModel
            {
                ManagementUnit = ManagmentUnit,
                AllotmentYears = _context.Allotments.AsNoTracking()
                                            .Where(a => a.ManagementUnitID == id)
                                            //.Where(a => a.TDate.Year >= DateTime.Now.Year)
                                            .OrderBy(a => a.Date.Year)
                                            .Select(a => a.Date.Year)
                                            .Distinct()
                                            .ToList()
            };

            return View("View", viewManagmentUnitViewModel);
        }

        public IActionResult ViewAllotments(long id, long year)
        {
            //ManagmentUnit ManagmentUnit = await _context.ManagmentUnits.AsNoTracking().SingleAsync(d => d.Id == id);
            IList<Allotment> allotments = _context.Allotments.AsNoTracking()
                                                    .Where(a => a.ManagementUnitID == id)
                                                    .Where(a => a.Date.Year == year)
                                                    .OrderBy(a => a.Date)
                                                    .ToList();

            return View(allotments);


        }

        public async Task<IActionResult> Edit(long id)
        {
            ManagementUnit ManagmentUnit = await _context.ManagementUnits.AsNoTracking().SingleAsync(d => d.Id == id);

            if (ManagmentUnit == null)
            {
                return NotFound();
            }

            return View(ManagmentUnit);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(long id, ManagementUnit ManagmentUnit)
        {
            if (id != ManagmentUnit.Id)
            {
                return BadRequest();
            }
            if (ModelState.IsValid)
            {
                if (ManagmentUnit.Name != "")
                {
                    _context.Entry(ManagmentUnit).State = EntityState.Modified;
                    await _context.SaveChangesAsync();
                } else
                {
                    return View(ManagmentUnit);
                }
            }
            return Redirect("/ManagmentUnit/View/" + id);
        }

        public IActionResult Add()
        {
            return View("Add");
        }

    }
}

CCMS/Controllers/TimeOffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CCMS.Areas.Identity.Data;
using CCMS.Models;
using CCMS.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace CCMS.Controllers
{
    [Authorize]
    public class TimeOffController : Controller
    {
        private readonly CCMSContext _context;
        private readonly UserManager<CCMSUser> _userManager;
        private readonly SignInManager<CCMSUser> _signInManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public TimeOffController(
            CCMSContext context,
            UserManager<CCMSUser> userManager,
            SignInManager<CCMSUser> signInManager,
            RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }

        [Authorize(Roles = "WFM, Admin, Human Resources")]
        public IActionResult Index()
        {
            IList<TimeOffRequest> timeOffRequests = _context.TimeOffRequests.ToList();
            return View(timeOffRequests);
        }

        [Authorize(Roles = "WFM, Admin, Human Resources, Staff")]
        public IActionResult Add()
        {
            AddTimeOffRequestViewModel addTimeOffRequestViewModel = new AddTimeOffRequestViewModel { };
            
            return View(addTimeOffRequestViewModel);
        }

        [Authorize(Roles = "WFM, Admin, Human Resources, Staff")]
        [HttpPost]
        public IActionResult Add(AddTimeOffRequestViewModel addTimeOffRequestViewModel)
        {
            if (ModelState.IsValid)
            {
                Employee employeeUser = _context.Employees.Single(e => e.Id.ToString() == _userManager.GetUserName(User));

                TimeOffAllowed timeOffAllowed = _context.TimeOffAlloweds
                                                .Where(t => t.EmployeeId == employeeUser.Id)
                                                .Where(t => t.Year == addTimeOffRequestViewModel.Date.Date.Year)
                                                .Single();
                if (timeOffAllowed.UTO >= 8 || timeOffAllowed.PTO >= 8)
                {
                    Allotment allotment = _context.Allotments
                                                    .Where(a => a.ManagementUnitID == employeeUser.ManagementUnitId)
                                                    .Where(a => a.Date == addTimeOffRequestViewModel.Date.Date)
                                                    .Single();

                    int allotmentTimeOffTaken = _context.TimeOffRequests
                                                    .Where(t => t.Date == addTimeOffRequestViewModel.Date.Date)
                                                    .Where(t => t.Requester.ManagementUnitId == employeeUser.ManagementUnitId)
                                                    .Count() * 8;

                    int employeeTimeOffTaken = _context.TimeOffRequests
                                                    .Where(t => t.Date.Year == addTimeOffRequestViewModel.Date.Date.Year)
                                                    .Where(t => t.RequesterId == employeeUser.Id)
                                                    .Count() * 8;

                    if (allotmentTimeOffTaken + 8 <= allotment.Allowed && employeeTimeOffTaken + 8 <= timeOffAllowed.PTO)
                    {
                        TimeOffRequest newTimeOffRequest = new TimeOffRequest
                        {
                            Date = addTimeOffRequestViewModel.Date.Date,
                            Requester = employeeUser,
                            SubmissionTimeStamp = DateTime.Now,
                            Status = "Approved"
                        };

                        _context.TimeOffRequests.Add(newTimeOffRequest);
                        _context.SaveChanges();

                        return Redirect("/TimeOff/" + newTimeOffRequest.ToString());
                    }
                    else
                    {
                        return View();
                    }
                }
                else
                {
                    return View();
                }
            }
            else
            {
                return View();
            }
        }
    }
}

CCMS/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Identity
@using CCMS.Areas.Identity.Data
@using Microsoft.AspNetCore.Authorization
@inject SignInManager<CCMSUser> SignInManager
@inject UserManager<CCMSUser> UserManager
@inject IAuthorizationService AuthorizationService
@inject CCMSContext Context

@{
    ViewData["Title"] = "Home Page";
}
<h1>Dashboard</h1>

@if (SignInManager.IsSignedIn(User))
{
    var employee = Context.Employees.Single(e => e.Id.ToString() == UserManager.GetUserName(User));
    <h4>Self</h4>
    <p><a asp-controller="Employee" asp-action="View" asp-route-id=@employee.Id>Time Off Balances</a></p>
    <p><a asp-controller="TimeOff" asp-action="Add">Request Time Off</a></p>
    @if ((await AuthorizationService.AuthorizeAsync(User, "RequireWFMRole")).Succeeded)
    {
        <h4>Entity Management</h4>

        <p><a asp-controller="ManagementUnit" asp-action="Index">Management Unit</a></p>
        <p><a asp-controller="Employee" asp-action="Index">Employee</a></p>
    }
    //var employee = Context.Employees.Single(e => e.Id.ToString() == if;
    //var role = RoleManager.Roles.Where(r => r.)
}

CCMS/Views/Home/Playground.cshtml
@{
    ViewData["Title"] = "Playground";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Playground</h1>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#addModal">Add Employee</button>

<table class="table">
    <tr>
        <th>First Name</th>
        <th>Middle Name</th>
        <th>Last Name</th>
        <th>Date of Hire</th>
    </tr>
    <tbody id="employees"></tbody>
</table>

<div class="modal" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Edit Employee</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <input type="hidden" class="form-control" id="edit-id">
                    </div>
                    <div class="form-group">
                        <label for="edit-fname" class="col-form-label">First Name</label>
                        <input type="text" class="form-control" id="edit-fname">
                    </div>
                    <div class="form-group">
                        <label for="edit-mname" class="col-form-label">Middle Name</label>
                        <input type="text" class="form-control" id="edit-mname">
                    </div>
                    <div class="form-group">
                        <label for="edit-lname" class="col-form-label">Last Name</label>
                        <input type="text" class="form-control" id="edit-lname">
                    </div>
                    <div class="form-group">
                        <label for="edit-hire-date" class="col-form-label">Date of Hire</label>
                        <input type="date" class="form-control" id="edit-hire-date">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="editEmployee()">Save</button>
            </div>
        </div>
    </div>
</div>

<div class="modal" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addModal">Add Employee</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="add-fname" class="col-form-label">First Name</label>
                        <input type="text" class="form-control" id="add-fname">
                    </div>
                    <div class="form-group">
                        <label for="add-mname" class="col-form-label">Middle Name</label>
                        <input type="text" class="form-control" id="add-mname">
                    </div>
                    <div class="form-group">
                        <label for="add-lname" class="col-form-label">Last Name</label>
                        <input type="text" class="form-control" id="add-lname">
                    </div>
                    <div class="form-group">
                        <label for="add-hire-date" class="col-form-label">Date of Hire</label>
                        <input type="date" class="form-control" id="add-hire-date">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" onclick="addEmployee()">Add</button>
            </div>
        </div>
    </div>
</div>